### ISSUE TITLE
How did you get the .shortcut files?

### ISSUE THREAD

**Issue by bwang514** [heliomass/iOSShortcuts#6]
Hi Daniel,

Thanks for creating this wonderful repo. I'm wondering how did you get these .shortcut files? I've tried to download them from an online gallery but I couldn't download the raw files on a laptop. 
The only way I can download them is using an iOS device, and it will directly open the shortcuts app. So I can't access the raw files. Also do you know if there's any better way to intepret the .shortcuts files? I try to open one of your shortcuts with Xcode, I can somehow understand the structure but wonder if there's any documentation?

Thanks a lot!
Bryan

**Comment by heliomass** [comment]
Hi Bryan,

Thanks for the feedback and I'm glad you like the repo!

> I'm wondering how did you get these .shortcut files? I've tried to download them from an online gallery but I couldn't download the raw files on a laptop.

Here's where it gets confusing. Up until iOS 12, it was possible to export Shortcuts as those `.shortcut` files you mention. When I created the repo back then, this was how I shared the Shortcuts. (If you're on an older version of iOS, you can still access these: [iOS 12](https://github.com/heliomass/iOSShortcuts/tree/v2), [iOS 11](https://github.com/heliomass/iOSShortcuts/tree/v1))

When iOS 13 / iPad OS came along, and Apple "baked" the Shortcuts app into iOS instead of distributing it as a standalone app, they secure the way Shortcuts are shared. Now, you can only share them via iCloud links.

I believe there's still ways you can export Shortcuts by creating a dedicated Shortcut to do this, but I don't think there's any way of importing a modified Shortcut back into the app this way.

I hope this helps,

Daniel.

**Comment by bwang514** [comment]
Thanks for answering, Daniel! What you said is exactly to what I later found out! Hope this issue would also help people who are also interested in playing with Shortcusts :)
